image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - Test acceptation
  - Release image
   - Deploy staging
  - Deploy prod


docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t  alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar    

test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < alpinehelloworld.tar # on demande à test acceptation de charger notre artefact
    - docker rm -f webapp # Nettoyage
    - docker run -d -p 80:5000 -e PORT=5000 --name webapp alpinehelloworld
    - sleep 5 # Attendre que le conteneur soit prêt
    - apk --no-cache add curl # Installer curl
    - curl "http://docker" | grep  "Hello world!"

release image:
  stage: Release image
  script:
    - docker load < alpinehelloworld.tar
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://${HOSTNAME_DEPLOY_STAGING}
  variables:
    HEROKU_APP: haykein-staging
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku@9.3.0
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" registry.heroku.com/${HEROKU_APP}/web
    - heroku container:login
    - docker push registry.heroku.com/${HEROKU_APP}/web
    - heroku stack:set container -a ${HEROKU_APP}
    - heroku container:release web -a ${HEROKU_APP}


deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://${HOSTNAME_DEPLOY_PROD} # eg: url_a_recuperer_sur_heroku
  variables:
    HEROKU_APP: haykein-prod
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku@9.3.0
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" registry.heroku.com/${HEROKU_APP}/web
    - heroku container:login
    - docker push registry.heroku.com/${HEROKU_APP}/web
    - heroku stack:set container -a ${HEROKU_APP}
    - heroku container:release web -a ${HEROKU_APP}
